version: "2"
services:
  test:
    environment:
      DATABASE_ODATA_URL: postgres://postgres@test-postgres/test
      DATABASE_URL: postgres://postgres@test-postgres-django/test_django
      ES_HOST: es
      ES_PORT: 9200
      DATAHUB_SECRET: abc
      KORBEN_SENTRY_DSN: http://abc:xyz@etc.com/etc/123
      REDIS_URL: tcp://test-redis
      UNIT_TESTS: "yes"
      CODECOV_TOKEN: ${CODECOV_TOKEN}
      CIRCLECI: ${CIRCLECI}
      CI: ${CI}
      CIRCLE_PROJECT_USERNAME: ${CIRCLE_PROJECT_USERNAME}
      CIRCLE_PROJECT_REPONAME: ${CIRCLE_PROJECT_REPONAME}
      CIRCLE_BRANCH: ${CIRCLE_BRANCH}
      CIRCLE_TAG: ${CIRCLE_TAG}
      CIRCLE_SHA1: ${CIRCLE_SHA1}
      CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}
      CIRCLE_COMPARE_URL: ${CIRCLE_COMPARE_URL}
      CIRCLE_BUILD_URL: ${CIRCLE_BUILD_URL}
      CIRCLE_BUILD_NUM: ${CIRCLE_BUILD_NUM}
      CIRCLE_PREVIOUS_BUILD_NUM: ${CIRCLE_PREVIOUS_BUILD_NUM}
      CI_PULL_REQUESTS: ${CI_PULL_REQUESTS}
      CI_PULL_REQUEST: ${CI_PULL_REQUEST}
      CIRCLE_ARTIFACTS: ${CIRCLE_ARTIFACTS}
      CIRCLE_USERNAME: ${CIRCLE_USERNAME}
      CIRCLE_TEST_REPORTS: ${CIRCLE_TEST_REPORTS}
      CIRCLE_PR_USERNAME: ${CIRCLE_PR_USERNAME}
      CIRCLE_PR_REPONAME: ${CIRCLE_PR_REPONAME}
      CIRCLE_PR_NUMBER: ${CIRCLE_PR_NUMBER}
    build:
      context: .
    links:
      - test-postgres
      - test-postgres-django
      - test-redis
    command: ./test-runner.sh test/tier0
  test-postgres:
    image: postgres:9.5
    environment:
      POSTGRES_DB: test
  test-postgres-django:
    image: postgres:9.5
    environment:
      POSTGRES_DB: test_django

  test-redis:
    image: redis:3.2.5
