version: "2"
services:
  test:
    build:
      context: .
    environment:
      KORBEN_SENTRY_DSN: http://abc:xyz@etc.com/etc/123
      UNIT_TESTS: "yes"
      CODECOV_TOKEN: ${CODECOV_TOKEN}
      CIRCLECI: ${CIRCLECI}
      CI: ${CI}
    command: ./test-runner.sh test/unit

  redis:
    image: redis:3.2.5
    volumes:
      - ./docker-volumes/test-redis-unit:/data
