# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_number', models.CharField(max_length=8, verbose_name='Company number')),
                ('company_name', models.CharField(max_length=160, verbose_name='Company name')),
                ('registered_address_care_of', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address care of')),
                ('registered_address_po_box', models.CharField(blank=True, max_length=10, null=True, verbose_name='Address POBox')),
                ('registered_address_address_1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 1 (House number and street')),
                ('registered_address_address_2', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address line 2 (area)')),
                ('registered_address_town', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address town')),
                ('registered_address_county', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address county')),
                ('registered_address_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address country')),
                ('registered_address_postcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address postcode')),
                ('company_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company category')),
                ('company_status', models.CharField(blank=True, max_length=70, null=True, verbose_name='Company status')),
                ('country_of_origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country of origin')),
                ('dissolution_date', models.DateField(blank=True, null=True, verbose_name='Dissolution date')),
                ('incorporation_date', models.DateField(blank=True, null=True, verbose_name='Incorporation date')),
                ('accounts_accounting_ref_day', models.IntegerField(blank=True, null=True, verbose_name='Accounts accounting ref day')),
                ('accounts_accounting_ref_month', models.IntegerField(blank=True, null=True, verbose_name='Accounts accounting ref month')),
                ('accounts_next_due_date', models.DateField(blank=True, null=True, verbose_name='Accounts next due date')),
                ('accounts_last_made_up_date', models.DateField(blank=True, null=True, verbose_name='Accounts last made up date')),
                ('accounts_category', models.CharField(blank=True, help_text='Accounts type description', max_length=30, null=True, verbose_name='Accounts category')),
                ('returns_next_due_date', models.DateField(blank=True, null=True, verbose_name='Returns next due date')),
                ('returns_last_made_up_date', models.DateField(blank=True, null=True, verbose_name='Returns last made up date')),
                ('mortgages_num_mort_charges', models.IntegerField(blank=True, null=True)),
                ('mortgages_num_mort_outstanding', models.IntegerField(blank=True, null=True)),
                ('mortgages_num_mort_part_satisfied', models.IntegerField(blank=True, null=True)),
                ('mortgages_num_mort_satisfied', models.IntegerField(blank=True, null=True)),
                ('sic_code_1', models.CharField(blank=True, max_length=170, null=True)),
                ('sic_code_2', models.CharField(blank=True, max_length=170, null=True)),
                ('sic_code_3', models.CharField(blank=True, max_length=170, null=True)),
                ('sic_code_4', models.CharField(blank=True, max_length=170, null=True)),
                ('limited_partnerships_num_gen_partners', models.IntegerField(blank=True, null=True)),
                ('limited_partnerships_num_lim_partners', models.IntegerField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_name_1_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_1_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_2_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_2_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_3_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_3_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_4_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_4_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_5_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_5_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_6_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_6_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_7_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_7_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_8_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_8_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_9_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_9_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('previous_name_10_change_of_name_date', models.DateField(blank=True, null=True)),
                ('previous_name_10_company_name', models.CharField(blank=True, max_length=160, null=True)),
                ('url', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
    ]
